# see also https://docs.gitlab.com/ce/ci/variables/README.html
stages:
  - build
  - test
  - release
  - cleanup

before_script:
  - echo $CI_SERVER_NAME
  - export COMPOSE_PROJECT_NAME=buildpipeline${CI_PIPELINE_ID}${CI_BUILD_NAME}
  - export APP_VERSION=$(git describe --always --dirty)
  - export STACK_PHP_IMAGE=${REGISTRY_HOST}/${CI_PROJECT_PATH}/php:${APP_VERSION}
  - export STACK_PHP_IMAGE_LATEST=${REGISTRY_HOST}/${CI_PROJECT_PATH}/php:latest
  - cd project/tests
  - cp .env-dist .env
  # ensure a Docker image with correct version exists
  - make version build

after_script:
  # set docker-compose isolation
  - export COMPOSE_PROJECT_NAME=buildpipeline${CI_PIPELINE_ID}${CI_BUILD_NAME}
  - cd project/tests
  - cp .env-dist .env
  - docker-compose down -v

test:
  stage: test
  script:
    - make all run-tests
  artifacts:
    paths:
      - tests-modules/codeception/_log
    when: always

lint:
  stage: test
  script:
    - make lint
  artifacts:
    paths:
      - tests-modules/codeception/_log
    when: always

release:latest:
  stage: release
  script:
    - docker tag ${STACK_PHP_IMAGE} ${STACK_PHP_IMAGE_LATEST}
    - docker push ${STACK_PHP_IMAGE_LATEST} || exit 1
  only:
    - latest

release:tags:
  stage: release
  script:
    - docker push ${STACK_PHP_IMAGE} || exit 1
  only:
    - release
    - tags