# see also https://docs.gitlab.com/ce/ci/variables/README.html
before_script:
  - export ISOLATION=buildpipeline${CI_PIPELINE_ID}
  - export APP_VERSION=$(git describe --always --dirty)
  - export STACK_PHP_IMAGE=${REGISTRY_HOST}/${CI_PROJECT_PATH}/php:${APP_VERSION}
  - export STACK_PHP_IMAGE_LATEST=${REGISTRY_HOST}/${CI_PROJECT_PATH}/php:latest
  - export COMPOSE_PROJECT_NAME=${ISOLATION}
  - cd tests
  - cp .env-dist .env

stages:
  - build
  - test
  - release
  - cleanup

build:
  stage: build
  script:
    - docker-compose build --pull

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose run --rm php codecept run cli,unit,functional,e2e
  artifacts:
    paths:
      - tests/codeception/_output
    when: always

release:latest:
  stage: release
  script:
    - docker tag ${STACK_PHP_IMAGE} ${STACK_PHP_IMAGE_LATEST}
    - docker push ${STACK_PHP_IMAGE_LATEST} || exit 1
  only:
    - latest

release:tags:
  stage: release
  script:
    - docker push ${STACK_PHP_IMAGE} || exit 1
  only:
    - release
    - tags

cleanup:
  stage: cleanup
  script:
    - docker-compose kill
    - docker-compose down -v
  when: always