# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '2.1'
services:

  php:
    build: .
    ports:
      - 21080:80
    depends_on:
      - db
      - redis
      - mailcatcher
    environment:
      # Database
      - DB_ENV_MYSQL_ROOT_PASSWORD=secret

      # Development settings, set your production defaults in Dockerfile
      - ENV_LOCAL_FILE=../project/config/local.env
      #- GITHUB_API_TOKEN=${GITHUB_API_TOKEN}

      # Development ONLY settings, DO NOT set production defaults for these values in Dockerfile
      - APP_ADMIN_PASSWORD=admin1
      - APP_ADMIN_EMAIL=admin@test.local
      - APP_MIGRATION_LOOKUP=@app/migrations/demo-data
      - APP_MAILER_USE_FILE_TRANSPORT=1

    volumes:
      # Application source-code
      - ./project/:/app/project:cached
      # Vendor source-code
      - ./vendor:/app/vendor:delegated
      # For composer usage in container; NOTE! There may be performance issues, see also https://github.com/docker/for-mac/issues/77
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./composer.json:/app/composer.json:cached
      - ./composer.lock:/app/composer.lock:cached

  db:
    #command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'

  mailcatcher:
    image: nisenabe/mailcatcher
    ports:
      - '1080'