# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '2'
services:

  php:
    build:
      dockerfile: Dockerfile
      context: .
      #args:
      #  - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    ports:
      - 21080:80
    depends_on:
      - db
    environment:
      # Database
      - MYSQL_ROOT_PASSWORD=secret
      # For host-volume development (permissions)
      - PHP_USER_ID=1000
      #- GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      #
      # Development settings, set your production defaults in Dockerfile
      - APP_NAME=dev-planck
      - APP_TITLE=PlanckDEV
      - APP_LANGUAGES=en,de,ru
      # Development ONLY settings, DO NOT set production defaults for these values in Dockerfile
      - APP_ADMIN_PASSWORD=admin1
      - APP_MIGRATION_LOOKUP=@app/migrations/demo-data
    volumes:
      # Application source-code
      - ./src/modules:/app/src/modules
      # Local development overrides for application ENV variables; NOTE: You need to create the file _before_ enabling the volume
      #- ./src/local.env:/app/src/local.env
      # For composer usage in container; NOTE! There may be performance issues, see also https://github.com/docker/for-mac/issues/77
      - ~/.composer/cache:/root/.composer/cache
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      # Debug
      #- ./web/assets:/app/web/assets
      #- ./runtime:/app/runtime

  worker:
    build: .
    depends_on:
      - db

  db:
    #command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'
