# Local stack overrides
#
# Variables are populated with values from `.env`
#
version: '2.2'
services:

  php:
    volumes:
      # Debug
      #- ./web/assets:/app/web/assets
      - ./runtime:/app/runtime